_target_: federated_methods.ppbc.ppbc.PPBC

theta: 0.2
gamma: 1
distribution: ???

epoch_method: 'gradient_angles'
epoch_k: 3

iter_method: 'loss'
iter_k: 1

iterations: 3
need_errors: True

beta : 0.1
trust_sample_amount: 500
prob_d: 0.1
