_target_: federated_methods.ppbc.ppbc.PPBC


method: 'scaffold'
theta: 0
gamma: 1

epoch_method: 'random'
epoch_k: 3

iter_method: 'random'
iter_k: 1

iterations: 3
need_errors: False

beta : 0.1
trust_sample_amount: 500
q_m: 1.0
