_target_: federated_methods.ppbc.ppbc.PPBC


method: 'scaffold'
theta: 0.2
gamma: 1

epoch_method: 'random'
epoch_k: 10

iter_method: 'random'
iter_k: 10

iterations: 1
need_errors: True

beta : 0.1
trust_sample_amount: 500
q_m: 1.0
