data_name: "cifar10"
data_sources:
    train_directories: ["/home/aletovv/federated_research/cifar10_hospitals/image_data/cifar_train_map_file_10clients.csv"]
    test_directories: ["/home/aletovv/federated_research/cifar10_hospitals/image_data/cifar_test_map_file.csv"]