data_name: food101_pathology
data_sources:
  test_directories: /home/valetov/EF25_NIPS/food101/image_data/food101_test_map_file.csv
  train_directories: /home/valetov/EF25_NIPS/food101/image_data/food101_pathology_map_file.csv
distribution_info: /home/valetov/EF25_NIPS/food101/image_data/pathology_additional_info.npy
