model_name: "inception1d"
config:
  _target_: ecglib.models.config.model_configs.InceptionNetConfig
  num_classes: 1 
  input_channels: 12
  kernel_size: 40
  depth: 6
  bottleneck_size: 32
  hidden_channels: 32
  use_residual: True
  hidden_channels_head: null
  prob_head: 0.5
  bn_final_head: False
  bn_head: True
  act_head: relu
  concat_pooling: True