model_name: "rnn1d"
config:
  _target_: ecglib.models.config.model_configs.RecurrentNetConfig
  input_channels: 12
  num_classes: 1
  lstm: True 
  hidden_dim: 256
  num_layers: 2
  bidirectional: False
  prob_head: 0.5
  bn_head: True
  act_head: relu
  hidden_channels_head: null